# Generated by Django 5.1.3 on 2024-11-14 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('blog', '0004_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(help_text='Author of the blog', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='author.author'),
        ),
    ]
